from queue import Queue
import threading
#NOTE: This is one of the most important files 

stop_sorting_flag = threading.Event() #Signals to the algorithms when to stop.

moves_queue = Queue()   #Stores the moves generated by the soting algorithms.