import sys
sys.dont_write_bytecode = True  #Prevents pycache; TODO:REMOVE THIS LINE BEFORE PROD

import tkinter as tk
from typing import Callable
from classes import Histogram, Colorstamp
from utils import *
from sorts import *
from queue import Queue
from time import sleep
import threading

WINDOW_COEFF = 0.5
WINDOW_HEIGHT = 1080
WINDOW_WIDTH = 1920

ARRAY_SIZE = 1000
Colors = True

window_resize_schedule_id = ""

sorts = {
    "Tri à bulles" : bubblesort,
    "Tri par sélection" : selectionsort,
    "Tri par sélection optimisé" : optimized_selectionsort,
    "Tri par insertion" : insertionsort,
    "Tri par fusion" : merge_sort
    }



"""Configuring window"""
root = tk.Tk()
root.geometry(f"{int(WINDOW_COEFF*WINDOW_WIDTH)}x{int(WINDOW_COEFF*WINDOW_HEIGHT)}")

root.grid_columnconfigure(0, weight=2)
root.grid_columnconfigure(1, weight=1)
root.grid_rowconfigure(0, weight=1)


canvas = tk.Canvas(root, background="black")
interface = tk.Frame(root, background="white", border=5)

canvas.grid(column=0, row=0, sticky="nsew")
interface.grid(column=1, row=0, sticky="nsew")

canvas_dimensions = get_dimensions(canvas)



"""HERE GOES THE LOGIC TO REPRESENT A LIST OF NUMBERS"""

#NOTE:Important variables
main_list = [Histogram(i, canvas, width=20) for i in range(ARRAY_SIZE)] #List that stores everything
ml = main_list  #alias for main_list

moves_queue = Queue()   #Stores the moves generated by the soting algorithms

main_list_updates:list[int] = []    #List that stores pending GUI updates
mlu = main_list_updates #alias for main_list_updates

colored_dict:dict[str, list[Colorstamp]] = {    #Dictionary that stores the colors used by the program.
    "red" : [],
    "blue" : [],
    "green" : []
}

#Initialising histograms
for index, histogram in enumerate(main_list):
    histogram.draw(position=index, hist_amount=len(ml))

def on_resize(event):
    """Canvas redrawing scheduler"""
    global window_resize_schedule_id

    if window_resize_schedule_id:   #checking if update is already scheduled
        root.after_cancel(window_resize_schedule_id)    #prevent new scheduling
    
    window_resize_schedule_id = root.after(70, resize_graph)    #Scheduling update


def resize_graph():
    """Updates the Graph dimensions according to the window size"""
    global window_resize_schedule_id, ml, canvas_dimensions

    window_resize_schedule_id = None
    canvas_dimensions = get_dimensions(canvas)

    root.after_idle(lambda: update_canvas_display(ml, force_update=True))
    


sorting = False
expired_stamps:Queue[Colorstamp] = Queue()
def update_colors():
    global colored_dict, amount_stamps_deleted
    global expired_stamps

    while sorting:

        for color in colored_dict.keys():

            colorstamps = colored_dict[color]

            valid_stamps = []

            for stamp in colorstamps:

                if stamp.is_expired():
                    expired_stamps.put(stamp)
                
                else:
                    valid_stamps.append(stamp)
            
            colored_dict[color] = valid_stamps
        sleep(0.016)
    return

def delete_old_colors():
    global expired_stamps
    while not expired_stamps.empty():
        expired_stamps.get().reset_color()



scheduled_animation_id:str
def animate(moves_list:Queue):
    """Animation function for the GUI. Given a list of moves, this funtion will replicate them on the GUI."""
    global ml, mlu, t1
    global scheduled_animation_id
    global sorting
    
    if moves_list.empty():
        print("waiting for moves to load!")
        scheduled_animation_id = root.after(1, lambda: animate(moves_list))
        return
    
    action = moves_list.get()

    match action[0]:
        
        case "swap":
            _, i, j = action
            ml[i].value, ml[j].value = ml[j].value, ml[i].value
            

            update_canvas_display(main_list=ml, pending_updates_list=[i, j])


            if Colors:
                colorstamp1 = ml[i].change_color("blue")
                colorstamp2 = ml[j].change_color("blue")
                colored_dict["blue"].extend((colorstamp1, colorstamp2))

        
        case "compare":
            if Colors:
                _, i, j = action
                colorstamp1 = ml[i].change_color("red")
                colorstamp2 = ml[j].change_color("red")
                colored_dict["red"].extend((colorstamp1, colorstamp2))
        
        case "set":
            _, i, value = action
            ml[i].value = value

            update_canvas_display(main_list=ml, pending_updates_list=[i])

            if Colors:
                colorstamp1 = ml[i].change_color("green")
                colored_dict["green"].append(colorstamp1)

        case "finished":
            print("list sorted!")
            sorting = False

            root.after(10, lambda: erase_colors(colored_dict=colored_dict, hist_list=main_list))

            listbox.config(state="normal")
            sort_button.config(state="active")
            stop_sort_button.config(state="disabled")
            randomise_button.config(state="active")

            return
    
    if Colors:
        delete_old_colors()
    
    scheduled_animation_id = root.after_idle(lambda: animate(moves_list))


def launch_sort(*args):
    global moves_queue, sorting
    sorting = True

    try:
        selection = listbox.curselection()
        selected_name = listbox.get(selection[0])

    except IndexError:
        print("Choisissez un mode de tri!")
        return

    func: Callable = sorts[selected_name]

    listbox.config(state="disabled")
    sort_button.config(state="disabled")
    stop_sort_button.config(state="active")
    randomise_button.config(state="disabled")
    
    t1 = threading.Thread(target=func, args=args, daemon=True)
    t1.start()

    t2 = threading.Thread(target=update_colors, args=[], daemon=True)
    t2.start()

    root.after(1, lambda: animate(moves_queue))

    return

def stop_animation():
    global scheduled_animation_id, moves_queue

    if scheduled_animation_id:
        root.after_cancel(scheduled_animation_id)
        stop_sort_button.config(text="Reprendre")
        scheduled_animation_id = ""
    else:
        scheduled_animation_id = root.after(1, lambda: animate(moves_queue))
        stop_sort_button.config(text="Pause")
    return


def change_color_state():
    """Used to switch between black and white/colred (b&w makes performance improvements)"""
    global Colors, visual_colors
    Colors = not Colors
    if Colors:
        visual_colors.config(text='Couleurs')
    else:
        visual_colors.config(text='Noir et Blanc')
    erase_colors(colored_dict, ml)



"""HERE GO THE BUTTONS OF THE INTERFACE"""
listbox = make_listbox(master=interface, sorts=sorts)   #Listbox to choose the algorithm
listbox.pack(fill="both", expand=True, padx=5, pady=1)

erase_colors_button = tk.Button(
    interface,
    text="Effacer couleurs",
    command=lambda: erase_colors(colored_dict=colored_dict, hist_list=main_list),
    width=50
    )

randomise_button = tk.Button(
    interface,
    text="Mélanger",
    command=lambda: shuffle_mainlist(main_list, colored_dict),
    width=50
    )

sort_button = tk.Button(
    interface,
    text="Trier",
    command=lambda: launch_sort(ml.copy(), moves_queue),    #use a copy of the list to avoid mutations while sorting
    width=50
    )

stop_sort_button = tk.Button(interface,
    text="Pause",
    command=stop_animation,
    width=50,
    state="disabled"
    )

visual_colors = tk.Button(
    interface,
    text="Couleurs",
    command=change_color_state,
    width=50
    )



erase_colors_button.pack(fill="both", expand=True, padx=5, pady=1)
randomise_button.pack(fill="both", expand=True, padx=5, pady=1)
sort_button.pack(fill="both", expand=True, padx=5, pady=1)
stop_sort_button.pack(fill="both", expand=True, padx=5, pady=1)
visual_colors.pack(fill="both", expand=True, padx=5, pady=1)


canvas.bind("<Configure>", on_resize)

root.mainloop()